<a href="https://colab.research.google.com/github/SanskarAgrahari-07/Machine-Learning/blob/main/ML4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
from sklearn.metrics import mean_squared_error, mean_absolute_percentage_error, r2_score

In [4]:
df = pd.read_excel('Lab Session Data.xlsx')
df = df.dropna(axis = 1)
df

Customer  Candies (#)  Mangoes (Kg)  Milk Packets (#)  Payment (Rs)
0      C_1           20             6                 2           386
1      C_2           16             3                 6           289
2      C_3           27             6                 2           393
3      C_4           19             1                 2           110
4      C_5           24             4                 2           280
5      C_6           22             1                 5           167
6      C_7           15             4                 2           271
7      C_8           18             4                 2           274
8      C_9           21             1                 4           148
9     C_10           16             2                 4           198

In [5]:
# Extracting matrix A and B from dataframe
A = df.iloc[:, 1:-1].values
B = df.iloc[:, -1].values

# Converting to numpy arrays
A = np.array(A)
B = np.array(B)

# Display matrix A and B
print("Matrix A:\n", A)
print("Matrix B:\n", B)

# Number of vectors in matrix A
noOfVector = A.shape[0]
print(f"Number of vectors: {noOfVector}")

# Dimensionality of matrices A and B
DimensionalityOfA = A.shape[1]
DimensionalityOfB = A.shape[1]  # Assuming B shares the same dimensionality
print(f"Dimensionality of A: {DimensionalityOfA}")
print(f"Dimensionality of B: {DimensionalityOfB}")

Matrix A:
 [[20  6  2]
 [16  3  6]
 [27  6  2]
 [19  1  2]
 [24  4  2]
 [22  1  5]
 [15  4  2]
 [18  4  2]
 [21  1  4]
 [16  2  4]]
Matrix B:
 [386 289 393 110 280 167 271 274 148 198]
Number of vectors: 10
Dimensionality of A: 3
Dimensionality of B: 3


In [6]:
rankOfMatrix = np.linalg.matrix_rank(A)
print("Rank of the given matrix A is", rankOfMatrix)

Rank of the given matrix A is 3


In [7]:
# Using Pseudo-Inverse find the cost of each product available for sale.
# (Suggestion: If you use Python, you can use numpy.linalg.pinv() function to get a
# pseudo-inverse.)

pseudoInverse = np.linalg.pinv(A)
priceEachProduct = pseudoInverse.dot(B)
priceEachProduct = np.array(priceEachProduct)
print(priceEachProduct)

[ 1. 55. 18.]


In [8]:
# . Use the Pseudo-inverse to calculate the model vector X for predicting the cost of the products
# available with the vendor.

X = np.dot(pseudoInverse, B)
print(X)

[ 1. 55. 18.]


In [9]:
# Create 'Category' column based on Payment being greater than 200
df['Category'] = df['Payment (Rs)'] > 200

# Replace True/False with 'RICH'/'POOR' in 'Category' column
df['Category'] = df['Category'].replace({True:'RICH', False: 'POOR'})

# Extract features from all columns except the first and last two
features = df.iloc[:, 1:-2].values

# Split the dataset into training and testing sets (80/20 split)
X_train, X_test, y_train, y_test = train_test_split(features, df['Category'], test_size=0.2, random_state=0)

# Initialize a RandomForest classifier model
clf = RandomForestClassifier()

# Train the classifier using the training data
clf.fit(X_train, y_train)

# Predict labels for the test dataset
y_pred = clf.predict(X_test)

# Calculate and print the accuracy of the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: ", accuracy)

# Display the modified DataFrame
df

Accuracy:  1.0


Customer  Candies (#)  Mangoes (Kg)  Milk Packets (#)  Payment (Rs) Category
0      C_1           20             6                 2           386     RICH
1      C_2           16             3                 6           289     RICH
2      C_3           27             6                 2           393     RICH
3      C_4           19             1                 2           110     POOR
4      C_5           24             4                 2           280     RICH
5      C_6           22             1                 5           167     POOR
6      C_7           15             4                 2           271     RICH
7      C_8           18             4                 2           274     RICH
8      C_9           21             1                 4           148     POOR
9     C_10           16             2                 4           198     POOR

In [10]:
from sklearn.preprocessing import LabelEncoder

# Example conversion of string labels to numerical labels
label_encoder = LabelEncoder()

# Fit the encoder on the actual data and transform both y_test and y_pred
y_test_encoded = label_encoder.fit_transform(y_test)
y_pred_encoded = label_encoder.transform(y_pred)

# Now calculate the MSE
mse = mean_squared_error(y_test_encoded, y_pred_encoded)
print(f"Mean Squared Error (MSE): {mse}")

Mean Squared Error (MSE): 0.0


In [11]:
# Calculate RMSE
rmse = np.sqrt(mse)
print(f"Root Mean Squared Error (RMSE): {rmse}")

# Calculate MAPE
mape = mean_absolute_percentage_error(y_test_encoded, y_pred_encoded)
print(f"Mean Absolute Percentage Error (MAPE): {mape * 100:.2f}%")

# Calculate R² score
r2 = r2_score(y_test_encoded, y_pred_encoded)
print(f"R² score: {r2}")

Root Mean Squared Error (RMSE): 0.0
Mean Absolute Percentage Error (MAPE): 0.00%
R² score: 1.0


In [12]:
# Set random seed for reproducibility
np.random.seed(42)

# Generate 20 data points with 2 features (X & Y) between 1 and 10
data_points = np.random.uniform(1, 10, size=(20, 2))

# Assign classes based on some condition, here we will assign class1 (Red) if the sum of X and Y is greater than 10, else class0 (Blue)
labels = np.array([1 if x[0] + x[1] > 10 else 0 for x in data_points])

# Separate the points by class for plotting
class0_points = data_points[labels == 0]
class1_points = data_points[labels == 1]

# Create scatter plot
plt.figure(figsize=(8, 6))
plt.scatter(class0_points[:, 0], class0_points[:, 1], color='red', label='Class 0')
plt.scatter(class1_points[:, 0], class1_points[:, 1], color='blue', label='Class 1')
plt.title('Scatter Plot of Generated Data Points')
plt.xlabel('Feature X')
plt.ylabel('Feature Y')
plt.legend()
plt.grid(True)
plt.show()

In [13]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler

# Example training data (replace these with your actual data)
# Simulated data for demonstration purposes
np.random.seed(0)  # For reproducibility
data_array = np.random.rand(100, 2) * 10  # 100 points in 2D space
actual_labels = np.random.choice(['Statement', 'Answer', 'Question'], 100)  # Random labels

# Encode labels to numbers (for kNN classifier)
label_map = {'Statement': 0, 'Answer': 1, 'Question': 2}
encoded_labels = np.array([label_map[label] for label in actual_labels])

# Train kNN classifier
k = 3
knn = KNeighborsClassifier(n_neighbors=k)
knn.fit(data_array, encoded_labels)

# Generate test set data
x = np.arange(0, 10.1, 0.1)
y = np.arange(0, 10.1, 0.1)
X_test, Y_test = np.meshgrid(x, y)
X_test = X_test.ravel()
Y_test = Y_test.ravel()
test_data = np.column_stack((X_test, Y_test))

# Classify test set data
predicted_labels = knn.predict(test_data)

# Decode predicted labels back to original class names
reverse_label_map = {0: 'Statement', 1: 'Answer', 2: 'Question'}
decoded_predicted_labels = np.array([reverse_label_map[label] for label in predicted_labels])

# Create scatter plot with updated colors and title
plt.figure(figsize=(10, 8))
scatter = plt.scatter(X_test, Y_test, c=predicted_labels, cmap='plasma', s=5, alpha=0.7)  # Changed cmap to 'plasma'
plt.colorbar(scatter, label='Predicted Class')
plt.xlabel('X-axis')
plt.ylabel('Y-axis')
plt.title('Scat of Test Data with Plasma Colors')
plt.grid(True)
plt.show()